# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctlptl < Formula
  desc "Making local Kubernetes clusters easy to set up and tear down"
  homepage "https://ctlptl.dev/"
  version "0.5.8"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tilt-dev/ctlptl/releases/download/v0.5.8/ctlptl.0.5.8.mac.arm64.tar.gz"
      sha256 "819b2ed08590635edf2c852def5bafc94033557ade8f8d137b92d7ee17a90fcb"
    end
    if Hardware::CPU.intel?
      url "https://github.com/tilt-dev/ctlptl/releases/download/v0.5.8/ctlptl.0.5.8.mac.x86_64.tar.gz"
      sha256 "fdf08b45795500a52566dab39bb9a3b6ed626503398d963d79cfc7bea9c0cc61"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tilt-dev/ctlptl/releases/download/v0.5.8/ctlptl.0.5.8.linux.arm64.tar.gz"
      sha256 "4a86cb782dfd51f7afff30fd2ba945b3b6587cf8a184b135b59c163c5eae895e"
    end
    if Hardware::CPU.intel?
      url "https://github.com/tilt-dev/ctlptl/releases/download/v0.5.8/ctlptl.0.5.8.linux.x86_64.tar.gz"
      sha256 "247330de95a39c8234266e64f82d078f0e4a16a5e4126e964eb15f379689ab8b"
    end
  end

  def install
    bin.install "ctlptl"
  end

  test do
    system "#{bin}/ctlptl version"
  end
end
