# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tilt < Formula
  desc "Tilt powers multi-service developments for teams that deploy to Kubernetes."
  homepage "https://tilt.dev/"
  version "0.22.7"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/tilt-dev/tilt/releases/download/v0.22.7/tilt.0.22.7.mac.x86_64.tar.gz"
    sha256 "880318b0524273e5963d0f3bc1e64700256d72446f7ae6f914e60f4662bdfc78"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/tilt-dev/tilt/releases/download/v0.22.7/tilt.0.22.7.mac.arm64_ALPHA.tar.gz"
    sha256 "7246b52abbe68d3861b8dce82f287d3310412a4f7ddbf7b817c877fc4e8d1e2c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/tilt-dev/tilt/releases/download/v0.22.7/tilt.0.22.7.linux.x86_64.tar.gz"
    sha256 "95db62f006663083bc134175ac308a1a90d758a91e17e1f5cb693155b1536d85"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/tilt-dev/tilt/releases/download/v0.22.7/tilt.0.22.7.linux.arm_ALPHA.tar.gz"
    sha256 "15132b91ddf0714d5253ed35298c7974698365fa87375e431599012773a130d4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/tilt-dev/tilt/releases/download/v0.22.7/tilt.0.22.7.linux.arm64_ALPHA.tar.gz"
    sha256 "38874fb8474db764d3f4800ffe795bc03b7f5dfc55281aa3514d674690317cc6"
  end

  def install
    bin.install "tilt"
  end

  test do
    system "#{bin}/tilt version"
    system "#{bin}/tilt verify-install"
  end
end
